export const mockData = [
  {
    ':@computed_region_fd5q_j34z': '676',
    accepts_child_care_subsidies: 'N',
    administrator_director_name: 'Dorcas  Weatherred',
    adverse_action: 'NO',
    conditions_on_permit: 'NO',
    corrective_action: 'NO',
    county: 'HALE',
    days_of_operation: 'Mon,Tue,Wed,Thu,Fri',
    deficiency_high: '5',
    deficiency_low: '0',
    deficiency_medium: '27',
    deficiency_medium_high: '14',
    deficiency_medium_low: '2',
    hours_of_operation: '08:00 AM-11:30 AM',
    issuance_date: '2012-04-30T00:00:00.000',
    licensed_to_serve_ages: 'Pre-Kindergarten,School',
    location_address: '1001 W 7TH ST  PLAINVIEW TX- 79072 7701',
    location_address_geo: { type: 'Point', coordinates: [-96.741505, 43.549887] },
    location_address_geo_address: '1001 W 7TH ST PLAINVIEW TX- 79072 7701',
    mailing_address: '1001 W 7TH ST  PLAINVIEW TX- 79072 7701',
    open_branch_offices: '0',
    open_foster_homes: '0',
    operation_id: '952508',
    operation_name: 'Calico Caboose LLC',
    operation_number: '1385206',
    operation_type: 'Licensed Center',
    phone_number: '8062933658',
    programs_provided: 'Snacks Provided,Transportation to/from School ,Field Trips',
    temporarily_closed: 'NO',
    total_assessments: '1',
    total_capacity: '45',
    total_inspections: '4',
    total_reports: '0',
    total_self_reports: '0',
    type_of_issuance: 'Full Permit'
  },
  {
    ':@computed_region_fd5q_j34z': '2827',
    accepts_child_care_subsidies: 'N',
    adverse_action: 'NO',
    conditions_on_permit: 'NO',
    corrective_action: 'NO',
    county: 'NAVARRO',
    days_of_operation: 'Mon,Tue,Wed,Thu,Fri',
    deficiency_high: '1',
    deficiency_low: '0',
    deficiency_medium: '1',
    deficiency_medium_high: '1',
    deficiency_medium_low: '0',
    email_address: 'acadhall@att.net',
    hours_of_operation: '06:00 AM-06:00 PM',
    issuance_date: '2004-12-10T00:00:00.000',
    licensed_to_serve_ages: 'Infant,Toddler,Pre-Kindergarten,School',
    location_address: '2805 LAFAYETTE ST  CORSICANA TX- 75110 1319',
    location_address_geo: { type: 'Point', coordinates: [-96.482907, 32.114987] },
    location_address_geo_address: '2805 LAFAYETTE ST CORSICANA TX- 75110 1319',
    mailing_address: '2805 LAFAYETTE ST  CORSICANA TX- 75110 1319',
    open_branch_offices: '0',
    open_foster_homes: '0',
    operation_id: '258036',
    operation_name: 'Annette Penney Hall',
    operation_number: '842631',
    operation_type: 'Registered Child-Care Home',
    phone_number: '9036541587',
    programs_provided: 'After School Care,Drop-In Care',
    temporarily_closed: 'NO',
    total_assessments: '0',
    total_capacity: '12',
    total_inspections: '2',
    total_reports: '0',
    total_self_reports: '0',
    type_of_issuance: 'Registered'
  },
  {
    ':@computed_region_fd5q_j34z': '2024',
    accepts_child_care_subsidies: 'N',
    administrator_director_name: 'Brenda Salmon',
    adverse_action: 'NO',
    conditions_on_permit: 'NO',
    corrective_action: 'NO',
    county: 'HARRIS',
    days_of_operation: 'Mon,Tue,Wed,Thu,Fri',
    deficiency_high: '1',
    deficiency_low: '0',
    deficiency_medium: '0',
    deficiency_medium_high: '0',
    deficiency_medium_low: '0',
    email_address: 'chasetxwh@brighthorizons.com',
    hours_of_operation: '07:00 AM-07:00 PM',
    issuance_date: '2001-05-11T00:00:00.000',
    licensed_to_serve_ages: 'Infant,Toddler,Pre-Kindergarten,School',
    location_address: '1010 WITTE RD  HOUSTON TX- 77055 6017',
    location_address_geo: { type: 'Point', coordinates: [-95.54005, 29.786943] },
    location_address_geo_address: '1010 WITTE RD HOUSTON TX- 77055 6017',
    mailing_address: '1010 WITTE RD  HOUSTON TX- 77055 6017',
    open_branch_offices: '0',
    open_foster_homes: '0',
    operation_id: '169865',
    operation_name: 'JP Morgan Chase Backup Center',
    operation_number: '554763',
    operation_type: 'Licensed Center',
    phone_number: '7132621940',
    programs_provided: 'Accredited,After School Care,Part Time Care',
    temporarily_closed: 'NO',
    total_assessments: '0',
    total_capacity: '117',
    total_inspections: '5',
    total_reports: '0',
    total_self_reports: '0',
    type_of_issuance: 'Full Permit'
  },
  {
    accepts_child_care_subsidies: 'N',
    administrator_director_name: 'Jose Izaguirre',
    adverse_action: 'NO',
    conditions_on_permit: 'NO',
    corrective_action: 'NO',
    county: 'CAMERON',
    deficiency_high: '0',
    deficiency_low: '0',
    deficiency_medium: '2',
    deficiency_medium_high: '3',
    deficiency_medium_low: '1',
    hours_of_operation: '12:00 AM-',
    issuance_date: '2014-01-03T00:00:00.000',
    licensed_to_serve_ages: '10-17',
    location_address: '401 E BUSINESS HWY 77  SAN BENITO TX- 78586',
    location_address_geo_address: '401 E BUSINESS HWY 77 SAN BENITO TX- 78586',
    mailing_address: '401 E BUSINESS HWY 77  SAN BENITO TX- 78586',
    open_branch_offices: '0',
    open_foster_homes: '0',
    operation_id: '1110140',
    operation_name: 'Southwest Key Programs Inc - Casa Rio Grande',
    operation_number: '1514002',
    operation_type: 'General Residential Operation',
    phone_number: '9562477400',
    programmatic_services: 'Child Care',
    temporarily_closed: 'NO',
    total_assessments: '0',
    total_capacity: '160',
    total_inspections: '23',
    total_reports: '3',
    total_self_reports: '9',
    type_of_issuance: 'Full Permit',
    website_address: 'www.swkey.org'
  },
  {
    accepts_child_care_subsidies: 'N',
    administrator_director_name: 'Susana  Alejandro',
    adverse_action: 'NO',
    conditions_on_permit: 'NO',
    corrective_action: 'NO',
    county: 'KERR',
    days_of_operation: 'Mon,Tue,Wed,Thu,Fri',
    deficiency_high: '0',
    deficiency_low: '0',
    deficiency_medium: '0',
    deficiency_medium_high: '1',
    deficiency_medium_low: '0',
    hours_of_operation: '06:45 AM-04:30 PM',
    issuance_date: '2005-08-12T00:00:00.000',
    licensed_to_serve_ages: 'Infant,Toddler,Pre-Kindergarten,School',
    location_address: 'CORNER OF TIVY AND 3RD ST  KERRVILLE TX- 78028',
    location_address_geo_address: 'CORNER OF TIVY AND 3RD ST KERRVILLE TX- 78028',
    mailing_address: '801 TIVY ST  KERRVILLE TX- 78028 3653',
    open_branch_offices: '0',
    open_foster_homes: '0',
    operation_id: '275252',
    operation_name: 'Tivy Child Development Center',
    operation_number: '850613',
    operation_type: 'Licensed Center',
    phone_number: '8302572246',
    programs_provided: 'After School Care,Field Trips',
    temporarily_closed: 'NO',
    total_assessments: '0',
    total_capacity: '72',
    total_inspections: '5',
    total_reports: '0',
    total_self_reports: '1',
    type_of_issuance: 'Full Permit',
    website_address: 'www.kerrvilleisd.net'
  },
  {
    ':@computed_region_fd5q_j34z': '790',
    accepts_child_care_subsidies: 'N',
    adverse_action: 'NO',
    conditions_on_permit: 'NO',
    corrective_action: 'NO',
    county: 'RANDALL',
    days_of_operation: 'Mon,Tue,Wed,Thu,Fri',
    deficiency_high: '0',
    deficiency_low: '0',
    deficiency_medium: '0',
    deficiency_medium_high: '0',
    deficiency_medium_low: '0',
    hours_of_operation: '07:30 AM-05:30 PM',
    issuance_date: '2006-08-22T00:00:00.000',
    licensed_to_serve_ages: 'Infant,Toddler,Pre-Kindergarten,School',
    location_address: '5302 GOODNIGHT TRL  AMARILLO TX- 79109 6309',
    location_address_geo: { type: 'Point', coordinates: [-101.889566, 35.150527] },
    location_address_geo_address: '5302 GOODNIGHT TRL AMARILLO TX- 79109 6309',
    mailing_address: '5302 GOODNIGHT TRL  AMARILLO TX- 79109 6309',
    open_branch_offices: '0',
    open_foster_homes: '0',
    operation_id: '299300',
    operation_name: 'Susan Denice Trew',
    operation_number: '862741',
    operation_type: 'Registered Child-Care Home',
    phone_number: '8063566176',
    programs_provided: 'School Age Care,Meals Provided ,After School Care,Snacks Provided,Drop-In Care,Part Time Care',
    temporarily_closed: 'NO',
    total_assessments: '0',
    total_capacity: '12',
    total_inspections: '1',
    total_reports: '0',
    total_self_reports: '0',
    type_of_issuance: 'Registered'
  },
  {
    accepts_child_care_subsidies: 'Y',
    adverse_action: 'NO',
    conditions_on_permit: 'YES',
    corrective_action: 'NO',
    county: 'TARRANT',
    days_of_operation: 'Mon,Tue,Wed,Thu,Fri',
    deficiency_high: '2',
    deficiency_low: '0',
    deficiency_medium: '1',
    deficiency_medium_high: '5',
    deficiency_medium_low: '0',
    hours_of_operation: '06:30 AM-06:00 PM',
    issuance_date: '2016-10-10T00:00:00.000',
    licensed_to_serve_ages: 'Infant,Toddler,Pre-Kindergarten,School',
    location_address: '3032 CLEMENTE DR  GRAND PRAIRIE TX- 75052 8735',
    location_address_geo_address: '3032 CLEMENTE DR GRAND PRAIRIE TX- 75052 8735',
    mailing_address: '3032 CLEMENTE DR  GRAND PRAIRIE TX- 75052 8735',
    open_branch_offices: '0',
    open_foster_homes: '0',
    operation_id: '1255774',
    operation_name: 'Leah Stanley',
    operation_number: '1634568',
    operation_type: 'Registered Child-Care Home',
    phone_number: '2144507884',
    programs_provided: 'School Age Care,Before School Care,Meals Provided ,After School Care,Snacks Provided',
    temporarily_closed: 'NO',
    total_assessments: '0',
    total_capacity: '12',
    total_inspections: '5',
    total_reports: '1',
    total_self_reports: '0',
    type_of_issuance: 'Registered'
  },
  {
    ':@computed_region_fd5q_j34z': '2080',
    accepts_child_care_subsidies: 'N',
    adverse_action: 'NO',
    conditions_on_permit: 'NO',
    corrective_action: 'NO',
    county: 'KAUFMAN',
    days_of_operation: 'Mon,Tue,Wed,Thu,Fri',
    deficiency_high: '0',
    deficiency_low: '0',
    deficiency_medium: '0',
    deficiency_medium_high: '0',
    deficiency_medium_low: '0',
    hours_of_operation: '06:30 AM-05:30 PM',
    issuance_date: '2017-08-01T00:00:00.000',
    licensed_to_serve_ages: 'Infant,Toddler,Pre-Kindergarten,School',
    location_address: '2057 ENCHANTED ROCK DR  FORNEY TX- 75126 0017',
    location_address_geo: { type: 'Point', coordinates: [-96.480783, 32.796011] },
    location_address_geo_address: '2057 ENCHANTED ROCK DR FORNEY TX- 75126 0017',
    mailing_address: '2057 ENCHANTED ROCK DR  FORNEY TX- 75126 0017',
    open_branch_offices: '0',
    open_foster_homes: '0',
    operation_id: '1284988',
    operation_name: 'Christy Marie Hardy',
    operation_number: '1658852',
    operation_type: 'Registered Child-Care Home',
    phone_number: '9723577304',
    programs_provided: 'Meals Provided ,After School Care,Snacks Provided,Drop-In Care,Part Time Care',
    temporarily_closed: 'NO',
    total_assessments: '0',
    total_capacity: '12',
    total_inspections: '1',
    total_reports: '0',
    total_self_reports: '0',
    type_of_issuance: 'Registered'
  },
  {
    ':@computed_region_fd5q_j34z': '3110',
    accepts_child_care_subsidies: 'N',
    adverse_action: 'NO',
    conditions_on_permit: 'NO',
    corrective_action: 'NO',
    county: 'COLLIN',
    days_of_operation: 'Mon,Tue,Wed,Thu,Fri,Sat',
    deficiency_high: '0',
    deficiency_low: '0',
    deficiency_medium: '0',
    deficiency_medium_high: '0',
    deficiency_medium_low: '0',
    hours_of_operation: '07:00 AM-07:30 PM',
    issuance_date: '2003-10-22T00:00:00.000',
    licensed_to_serve_ages: 'Infant,Toddler,Pre-Kindergarten,School',
    location_address: '5928 COLBY DR  PLANO TX- 75094 4542',
    location_address_geo: { type: 'Point', coordinates: [-96.618218, 33.008538] },
    location_address_geo_address: '5928 COLBY DR PLANO TX- 75094 4542',
    mailing_address: '5928 COLBY DR  PLANO TX- 75094 4542',
    open_branch_offices: '0',
    open_foster_homes: '0',
    operation_id: '234562',
    operation_name: 'Thu Tuyen Pham',
    operation_number: '832062',
    operation_type: 'Registered Child-Care Home',
    phone_number: '2147272327',
    programs_provided: 'Weekend Care',
    temporarily_closed: 'NO',
    total_assessments: '0',
    total_capacity: '12',
    total_inspections: '2',
    total_reports: '0',
    total_self_reports: '0',
    type_of_issuance: 'Registered'
  },
  {
    ':@computed_region_fd5q_j34z': '3027',
    accepts_child_care_subsidies: 'N',
    adverse_action: 'NO',
    conditions_on_permit: 'NO',
    corrective_action: 'NO',
    county: 'BEXAR',
    days_of_operation: 'Mon,Tue,Wed,Thu,Fri',
    deficiency_high: '0',
    deficiency_low: '0',
    deficiency_medium: '0',
    deficiency_medium_high: '1',
    deficiency_medium_low: '0',
    hours_of_operation: '07:00 AM-06:00 PM',
    issuance_date: '2017-09-13T00:00:00.000',
    licensed_to_serve_ages: 'Infant,Toddler,Pre-Kindergarten,School',
    location_address: '5919 PATRICK HENRY ST  SAN ANTONIO TX- 78233 5220',
    location_address_geo: { type: 'Point', coordinates: [-98.368713, 29.551025] },
    location_address_geo_address: '5919 PATRICK HENRY ST SAN ANTONIO TX- 78233 5220',
    mailing_address: '6246 PANTHER PEAK  SAN ANTONIO TX- 78247 6212',
    open_branch_offices: '0',
    open_foster_homes: '0',
    operation_id: '1281979',
    operation_name: 'Lisa Doak',
    operation_number: '1656327',
    operation_type: 'Registered Child-Care Home',
    phone_number: '2104809345',
    programs_provided: 'Meals Provided ,After School Care,Snacks Provided',
    temporarily_closed: 'NO',
    total_assessments: '0',
    total_capacity: '12',
    total_inspections: '3',
    total_reports: '0',
    total_self_reports: '0',
    type_of_issuance: 'Registered'
  }
];
